#!/usr/bin/python

import lxml.etree as et
import argparse
from tempfile import NamedTemporaryFile
import os
import re

parser = argparse.ArgumentParser(description='Create a platform xml for the scalability experiment')
parser.add_argument('--file', type=str, help='the name of the produced xml', required=True)
parser.add_argument('--nodes_count', type=int, help='the number of nodes involved in the simulation', required=True)
parser.add_argument('--is_for_java', action='store_true', help='if provided, the tool will produce a deployment xml to be used in Java experiment')

args = parser.parse_args()

root = et.Element('platform')
root.set('version', '4.1')

for i in range(0, args.nodes_count):
    actor = et.Element('actor')
    actor.set('host', 'node-' + str(i))
    actor.set('function', 'app.scalability.Peer' if args.is_for_java else 'peer')
    actorIdArgument = et.Element('argument')
    actorIdArgument.set('value', str(i))
    actorNodeCountArgument = et.Element('argument')
    actorNodeCountArgument.set('value', str(args.nodes_count))
    actor.append(actorIdArgument)
    actor.append(actorNodeCountArgument)
    root.append(actor)

tree = et.ElementTree(root)
tree.docinfo.system_url = 'http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd'
tree.write(args.file, xml_declaration=True, encoding="utf-8")
